from typing import Any

from markers._types import MemberInfo

class AllProxy:
    def __init__(self, registry_cls: type) -> None: ...
    @property
    def members(self) -> dict[str, list[MemberInfo]]: ...
    @property
    def fields(self) -> dict[str, list[MemberInfo]]: ...
    @property
    def methods(self) -> dict[str, list[MemberInfo]]: ...
    def __getattr__(self, marker_name: str) -> dict[str, list[MemberInfo]]: ...

class Registry:
    all: AllProxy
    fields: dict[str, MemberInfo]
    methods: dict[str, MemberInfo]
    members: dict[str, MemberInfo]
    def __init_subclass__(cls, abstract: bool = ..., **kwargs: Any) -> None: ...
    @classmethod
    def subclasses(cls) -> list[type]: ...
